### ISSUE TITLE
LSP7 NFT 2.0 Nomenclature

### ISSUE THREAD

**Issue by jxyang44** [lukso-network/docs#322]
https://docs.lukso.tech/standards/nft-2.0/LSP7-Digital-Asset describes, "LSP7-DigitalAsset is a standard that aims to describe **fungible** assets. The term **fungible** means that these assets are mutually interchangeable (e.g., one token has the same value as another token)."

But then the documents categorize LSP7 as a NFT 2.0 if tokens are indivisible. 
https://docs.lukso.tech/tools/lsp-factoryjs/deployment/digital-asset: "LSP7 is based on the ERC20 token standard and can be used as an NFT 2.0 contract by setting the isNFT constructor value to true when deploying. This will set the contract decimals value to 0 so that all tokens are indivisible."

This is really just semantics, but I think it is contradictory to describe a **fungible** token (by definition) as a NFT 2.0 (**non-fungible** token). Suggestion: use a different boolean name (e.g. _isDivisible) to represent divisibility, and don't use "NFT 2.0" to describe LSP7.

**Comment by Hugoo** [comment]
Hey! Thanks for opening the issue, it is a good point. We will discuss this with the team this week.

**Comment by jxyang44** [comment]
Thanks Hugo!

**Comment by YamenMerhi** [comment]
Hey @jxyang44 
It really depends on how you define fungible and non-fungible assets.
> Fungibility is the property of a good or a commodity whose individual units are essentially interchangeable and each of whose parts is indistinguishable from another part.

So if you are creating tickets or a token representing some bags, you will have indistinguishable units (all tickets or bags are looking the same) but at the same time, they are non-divisible.

I would say that if decimals are set to 0, they are non-fungible because you cannot exchange units of these tokens.

So with LSP7, we can create tokens & NFTs. Let's discuss and based on the discussion we see if we should edit the standards section or tools section 🚀

**Comment by Hugoo** [comment]
@YamenMerhi @CJ42 is this issue still relevant after all the changes you did lately?
Can we close this issue?

**Comment by YamenMerhi** [comment]
The boolean is changed from `isNFT` to `isNonDivisible`, thanks for opening the issue!
